### ISSUE TITLE
Classification of Transformers?

### ISSUE THREAD

**Issue by chadbrewbaker** [analysis-tools-dev/dynamic-analysis#23]
I'm calling them transformers for lack of a better term:

https://github.com/google/souper  - optimize LLVM IR with SMT solvers
https://github.com/facebookincubator/BOLT - profile guided permutation of linking to improve cache efficiency
https://github.com/google/llvm-propeller - profile guided hot/cold function splitting to improve cache efficiency
https://github.com/facebook/redex - Android byte code optimizer
https://github.com/facebookincubator/SPARTA  - Abstract analysis library behind ReDex
https://www.infoq.com/presentations/facebook-google-bpf-linux-kernel/ - eBPF - analysis built into the Linux Kernel 

Not sure they fit 100% in a "static" or "dynamic" classification - but I'm leaning towards dynamic?

**Comment by arthaud** [comment]
Redex and Sparta are definitely static analyzers, not dynamic.

**Comment by chadbrewbaker** [comment]
No hard opinion either way. Profile guided optimizations require execution - so dynamic. eBPF is dynamic?

How about Souper?

**Comment by mre** [comment]
Hey @chadbrewbaker,
first off thanks for listing those tools.
Apart from Redex and Sparta I'd be happy to include the tools in the list. Would you have time to create a PR?

**Comment by mre** [comment]
Merged those tools. Thanks for the recommendation @chadbrewbaker. Please keep 'em coming.
