### ISSUE TITLE
Are these tools awesome?

### ISSUE THREAD

**Issue by nvhaver** [analysis-tools-dev/dynamic-analysis#8]
Similar to my issue on the static analysis list: https://github.com/mre/awesome-static-analysis/issues/281

- [WhiteHat Sentinel Dynamic](https://www.whitehatsec.com/products/dynamic-application-security-testing/)
- [HCL AppScan Standard](https://www.hcltechsw.com/wps/portal/products/appscan/home/!ut/p/z1/04_Sj9CPykssy0xPLMnMz0vMAfIjo8zi_QO8nQ0MnQ0C_F3MnA0CHX2dvYN9woxNvEz0w1EVWDgGuQAVeLpbBvu6Gxl4m-hHUaLfxJQ4_QY4gKMBifZjKojCb3y4fhSqFe6Bpk5AEwIMTNyMfYzdfczQFWAJIrwKQGFAyBUFuaGhoREGmZ7piooAwLgEZw!!/?1dmy&urile=wcm%3apath%3a/wps/wcm/connect/hcl+software+content/products/appscan/offerings/standard)
- [Minded Security BlueClosure](https://www.mindedsecurity.com/index.php/products/blueclosure)
- [Code Dx Code Pulse](https://codedx.com/code-pulse/)

Ofc, I'd add these alphabetically to the list with sections like 'multilanguage'.

**Comment by mre** [comment]
Yup, looks good to me. Please go ahead and create a PR. 👍

**Comment by mre** [comment]
Ping @nvhaver. Maybe you find the time to do this PR for [Hacktoberfest](https://hacktoberfest.digitalocean.com/)? 😃
